name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -R

      - name: Print current working directory
        run: pwd

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }} ./strapi/examples/getstarted

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }}

      - name: Set image tag as output
        id: image_tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
