name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Debug: List repository contents
      - name: List repository contents
        run: ls -R

      # Debug: Print current working directory
      - name: Print current working directory
        run: pwd

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image from correct subdirectory
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }} ./examples/getstarted

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }}

      # Set image tag as output
      - name: Set image tag as output
        id: image_tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
