name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (if using Docker Hub, otherwise use ECR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Build the Docker image from correct subdirectory
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }} ./examples/getstarted

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }}

      # Set image tag as output
      - name: Set image tag as output
        id: image_tag
        run: echo "::set-output name=image_tag::${{ github.sha }}"
